### ISSUE TITLE
Invalid end tag in nuxt3-bootstrap5-template/app.vue

### ISSUE THREAD

**Issue by jdisco** [schmaiki/nuxt3-bootstrap5-template#1]
// nuxt3-bootstrap5-template/app.vue

---------ORIGINAL CODE-----------
```
<template>
  <div>
    <div class="bg-theme1 p-3">
      <NavBar />
      <br>
      <h1>Minimal Boostrap5 Template</h3>
    </div>
  </div>
</template>
```

--------THIS LINE--------
`      <h1>Minimal Boostrap5 Template</h3>`

--------NEEDS TO BE------------
`      <h1>Minimal Boostrap5 Template</h1>`

**Comment by schmaiki** [comment]
Thx
